-
  version: 3.0.0-alpha2-master
  image: Visual Studio 2017
  configuration: Release

  branches:
      only:
        - master
  
  before_build:
  - msbuild /t:restore Results.sln
  build:
    publish_nuget: true
    verbosity: minimal

  nuget:
      account_feed: true
      
  test_script:
    - cmd: dotnet test /OneModel.Results.Tests.csproj --no-build

  dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{version}'
      package_version: '{version}'